# Generated by Django 3.2.4 on 2021-06-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_photos/'),
        ),
    ]
